### ISSUE TITLE
Theme is not up-to-date

### ISSUE THREAD

**Issue by buzinas** [ngryman/codesandbox-theme#3]
It seems that the theme is not up-to-date.

![image](https://user-images.githubusercontent.com/7298695/61388130-ccb85b80-a88d-11e9-9e3c-93c843cb1197.png)

It doesn't look like with the screenshot on the README.

**Comment by ngryman** [comment]
That's weird, do you mind confirming you have the `1.1.3` version?

![](https://zappy.zapier.com/BEA22EC2-324B-478F-9E3B-DDC21D57058E.png)

**Comment by buzinas** [comment]
Yup, latest version.

![image](https://user-images.githubusercontent.com/7298695/61396620-7bfd2e80-a89e-11e9-9fda-4f0de7d643ad.png)

**Comment by NimishKashyap** [comment]
Hey I am having the same problem
Can you please figure it out?

**Comment by blasdfaa** [comment]
Same problem. Highlight doesn't match the theme

**Comment by ngryman** [comment]
Sorry for the late answer.
I just published `1.2.0` with the latest changes on `master`. Let me know if it's 👍

**Comment by blasdfaa** [comment]
> Sorry for the late answer.
> I just published `1.2.0` with the latest changes on `master`. Let me know if it's 👍

Nope, the problem remains. Everything is the same as in the screenshot above

**Comment by ngryman** [comment]
Got it, thanks for the quick feedback. I'll take a look then and try to publish a new version before EOW.

**Comment by vivere-dally** [comment]
Any updates on this?

**Comment by ngryman** [comment]
Sorry for the very late answer. Moving cities takes more energy than I thought 😅 

Ok, so it seems CodeSandbox has two other themes that this extension is not providing: `CodeSandbox Black` and `CodeSandbox Black 2021`. On `codesandbox.io`, the default one is `CodeSandbox Black` which is slightly different from this one. So I guess that explains the differences mentioned here.

I added these new themes to the extension and published a `2.0.0`: https://marketplace.visualstudio.com/items?itemName=ngryman.codesandbox-theme.

You now have these three themes available:
* `CodeSandbox Legacy`, which is the one provided by `1.2.0`. On `codesandbox.io` it's named `CodeSandbox`.
* `CodeSandbox Black` which is the default one in `codesandbox.io`.
* `CodeSandbox Black 2021`.

Hopefully, it should solve the issue. Let me know if it's 👍

**Comment by brams-dev** [comment]
Thank you for updating the extension!
Apologies if this is not the right place to ask, but would it be possible to publish the latest version on github too?
